//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/WFCTienda.Modelo")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_CPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_MPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_PField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descripcion_PField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Estado_PField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Imagen_PField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Precio_PField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Stock_PField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo_CP {
            get {
                return this.Codigo_CPField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_CPField, value) != true)) {
                    this.Codigo_CPField = value;
                    this.RaisePropertyChanged("Codigo_CP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo_MP {
            get {
                return this.Codigo_MPField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_MPField, value) != true)) {
                    this.Codigo_MPField = value;
                    this.RaisePropertyChanged("Codigo_MP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo_P {
            get {
                return this.Codigo_PField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_PField, value) != true)) {
                    this.Codigo_PField = value;
                    this.RaisePropertyChanged("Codigo_P");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion_P {
            get {
                return this.Descripcion_PField;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion_PField, value) != true)) {
                    this.Descripcion_PField = value;
                    this.RaisePropertyChanged("Descripcion_P");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado_P {
            get {
                return this.Estado_PField;
            }
            set {
                if ((object.ReferenceEquals(this.Estado_PField, value) != true)) {
                    this.Estado_PField = value;
                    this.RaisePropertyChanged("Estado_P");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen_P {
            get {
                return this.Imagen_PField;
            }
            set {
                if ((object.ReferenceEquals(this.Imagen_PField, value) != true)) {
                    this.Imagen_PField = value;
                    this.RaisePropertyChanged("Imagen_P");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio_P {
            get {
                return this.Precio_PField;
            }
            set {
                if ((this.Precio_PField.Equals(value) != true)) {
                    this.Precio_PField = value;
                    this.RaisePropertyChanged("Precio_P");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Stock_P {
            get {
                return this.Stock_PField;
            }
            set {
                if ((this.Stock_PField.Equals(value) != true)) {
                    this.Stock_PField = value;
                    this.RaisePropertyChanged("Stock_P");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clase", Namespace="http://schemas.datacontract.org/2004/07/WFCTienda.Modelo")]
    [System.SerializableAttribute()]
    public partial class Clase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_cpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estado_cpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_cpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo_cp {
            get {
                return this.codigo_cpField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_cpField, value) != true)) {
                    this.codigo_cpField = value;
                    this.RaisePropertyChanged("codigo_cp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado_cp {
            get {
                return this.estado_cpField;
            }
            set {
                if ((object.ReferenceEquals(this.estado_cpField, value) != true)) {
                    this.estado_cpField = value;
                    this.RaisePropertyChanged("estado_cp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre_cp {
            get {
                return this.nombre_cpField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_cpField, value) != true)) {
                    this.nombre_cpField = value;
                    this.RaisePropertyChanged("nombre_cp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marca", Namespace="http://schemas.datacontract.org/2004/07/WFCTienda.Modelo")]
    [System.SerializableAttribute()]
    public partial class Marca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_mpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_mpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo_mp {
            get {
                return this.codigo_mpField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_mpField, value) != true)) {
                    this.codigo_mpField = value;
                    this.RaisePropertyChanged("codigo_mp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre_mp {
            get {
                return this.nombre_mpField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_mpField, value) != true)) {
                    this.nombre_mpField = value;
                    this.RaisePropertyChanged("nombre_mp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listado", ReplyAction="http://tempuri.org/IService1/listadoResponse")]
        Tienda.ServiceReference1.Producto[] listado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listado", ReplyAction="http://tempuri.org/IService1/listadoResponse")]
        System.Threading.Tasks.Task<Tienda.ServiceReference1.Producto[]> listadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clases", ReplyAction="http://tempuri.org/IService1/clasesResponse")]
        Tienda.ServiceReference1.Clase[] clases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clases", ReplyAction="http://tempuri.org/IService1/clasesResponse")]
        System.Threading.Tasks.Task<Tienda.ServiceReference1.Clase[]> clasesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/marcas", ReplyAction="http://tempuri.org/IService1/marcasResponse")]
        Tienda.ServiceReference1.Marca[] marcas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/marcas", ReplyAction="http://tempuri.org/IService1/marcasResponse")]
        System.Threading.Tasks.Task<Tienda.ServiceReference1.Marca[]> marcasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Agregar", ReplyAction="http://tempuri.org/IService1/AgregarResponse")]
        string Agregar(Tienda.ServiceReference1.Producto reg, System.Web.HttpPostedFileBase archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Agregar", ReplyAction="http://tempuri.org/IService1/AgregarResponse")]
        System.Threading.Tasks.Task<string> AgregarAsync(Tienda.ServiceReference1.Producto reg, System.Web.HttpPostedFileBase archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Editar", ReplyAction="http://tempuri.org/IService1/EditarResponse")]
        string Editar(Tienda.ServiceReference1.Producto reg, System.Web.HttpPostedFileBase archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Editar", ReplyAction="http://tempuri.org/IService1/EditarResponse")]
        System.Threading.Tasks.Task<string> EditarAsync(Tienda.ServiceReference1.Producto reg, System.Web.HttpPostedFileBase archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Eliminar", ReplyAction="http://tempuri.org/IService1/EliminarResponse")]
        string Eliminar(string idprod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Eliminar", ReplyAction="http://tempuri.org/IService1/EliminarResponse")]
        System.Threading.Tasks.Task<string> EliminarAsync(string idprod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Buscar", ReplyAction="http://tempuri.org/IService1/BuscarResponse")]
        Tienda.ServiceReference1.Producto Buscar(string idprod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Buscar", ReplyAction="http://tempuri.org/IService1/BuscarResponse")]
        System.Threading.Tasks.Task<Tienda.ServiceReference1.Producto> BuscarAsync(string idprod);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Tienda.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Tienda.ServiceReference1.IService1>, Tienda.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tienda.ServiceReference1.Producto[] listado() {
            return base.Channel.listado();
        }
        
        public System.Threading.Tasks.Task<Tienda.ServiceReference1.Producto[]> listadoAsync() {
            return base.Channel.listadoAsync();
        }
        
        public Tienda.ServiceReference1.Clase[] clases() {
            return base.Channel.clases();
        }
        
        public System.Threading.Tasks.Task<Tienda.ServiceReference1.Clase[]> clasesAsync() {
            return base.Channel.clasesAsync();
        }
        
        public Tienda.ServiceReference1.Marca[] marcas() {
            return base.Channel.marcas();
        }
        
        public System.Threading.Tasks.Task<Tienda.ServiceReference1.Marca[]> marcasAsync() {
            return base.Channel.marcasAsync();
        }
        
        public string Agregar(Tienda.ServiceReference1.Producto reg, System.Web.HttpPostedFileBase archivo) {
            return base.Channel.Agregar(reg, archivo);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsync(Tienda.ServiceReference1.Producto reg, System.Web.HttpPostedFileBase archivo) {
            return base.Channel.AgregarAsync(reg, archivo);
        }
        
        public string Editar(Tienda.ServiceReference1.Producto reg, System.Web.HttpPostedFileBase archivo) {
            return base.Channel.Editar(reg, archivo);
        }
        
        public System.Threading.Tasks.Task<string> EditarAsync(Tienda.ServiceReference1.Producto reg, System.Web.HttpPostedFileBase archivo) {
            return base.Channel.EditarAsync(reg, archivo);
        }
        
        public string Eliminar(string idprod) {
            return base.Channel.Eliminar(idprod);
        }
        
        public System.Threading.Tasks.Task<string> EliminarAsync(string idprod) {
            return base.Channel.EliminarAsync(idprod);
        }
        
        public Tienda.ServiceReference1.Producto Buscar(string idprod) {
            return base.Channel.Buscar(idprod);
        }
        
        public System.Threading.Tasks.Task<Tienda.ServiceReference1.Producto> BuscarAsync(string idprod) {
            return base.Channel.BuscarAsync(idprod);
        }
    }
}
